export const customerCopy = {
  vi: { login: 'Đăng nhập', register: 'Tạo tài khoản', logout: 'Đăng xuất', name: 'Họ và tên', email: 'Email', password: 'Mật khẩu (tối thiểu 12 ký tự)', confirm: 'Xác nhận mật khẩu', mismatch: 'Mật khẩu xác nhận chưa khớp.', verify: 'Xác minh email', pending: 'Vui lòng xác minh email trước khi đặt lịch.', sent: 'Nếu email chưa được đăng ký, chúng tôi đã tạo tài khoản và gửi liên kết xác minh. Hãy kiểm tra hộp thư, sau đó đăng nhập để tiếp tục.', resend: 'Gửi lại email xác minh', resent: 'Đã tiếp nhận yêu cầu. Nếu vừa gửi email, vui lòng đợi ít nhất 60 giây.', verified: 'Email đã được xác minh. Bạn có thể tiếp tục đặt lịch.', invalid: 'Liên kết không hợp lệ, đã dùng hoặc hết hạn. Đăng nhập để gửi lại email xác minh.', continue: 'Tiếp tục đặt lịch', error: 'Không thể thực hiện. Vui lòng kiểm tra thông tin và thử lại.', unavailable: 'Dịch vụ tạm thời không khả dụng. Vui lòng thử lại.', rate: 'Bạn thao tác quá nhanh. Vui lòng đợi rồi thử lại.', credentials: 'Email hoặc mật khẩu không đúng.', loading: 'Đang tải…', bookings: 'Lịch hẹn của tôi', upcoming: 'Sắp tới', past: 'Đã qua', empty: 'Chưa có lịch hẹn.', meeting: 'Liên kết cuộc họp sẽ được cập nhật sau.', back: 'Quay lại', retry: 'Thử lại', next: 'Tiếp', previous: 'Trước', solution: 'Giải pháp / phân hệ', choose: 'Chọn giải pháp', hold: 'Giữ chỗ còn', expired: 'Chỗ giữ đã hết hạn. Vui lòng chọn lại thời gian.', acquire: 'Tiếp tục / Giữ chỗ', change: 'Đổi thời gian', conflict: 'Thời gian này không còn trống. Chỗ giữ trước đó (nếu còn hạn) được giữ nguyên.', releaseError: 'Chưa thể giải phóng chỗ. Vui lòng thử lại.', real: 'Lịch trống được cập nhật từ hệ thống. Chỗ chỉ được giữ khi bạn nhấn Tiếp tục.', success: 'Đã nhận yêu cầu. NeoTek sẽ xác nhận lịch hẹn qua email.', cancelled: 'Hủy / Quay lại', confirmBooking: 'Gửi yêu cầu đặt lịch', time: 'Thời gian', duration: 'Thời lượng' },
  en: { login: 'Sign in', register: 'Create account', logout: 'Sign out', name: 'Full name', email: 'Email', password: 'Password (at least 12 characters)', confirm: 'Confirm password', mismatch: 'Passwords do not match.', verify: 'Verify email', pending: 'Please verify your email before booking.', sent: 'If this email is new, your account was created and a verification link was sent. Check your inbox, then sign in to continue.', resend: 'Resend verification email', resent: 'Request accepted. If an email was just sent, please wait at least 60 seconds.', verified: 'Your email is verified. You can continue booking.', invalid: 'This link is invalid, already used or expired. Sign in to request another verification email.', continue: 'Continue booking', error: 'Unable to continue. Check your details and try again.', unavailable: 'Service temporarily unavailable. Please try again.', rate: 'Too many attempts. Please wait and try again.', credentials: 'Invalid email or password.', loading: 'Loading…', bookings: 'My bookings', upcoming: 'Upcoming', past: 'Past', empty: 'No bookings yet.', meeting: 'A meeting link will be added later.', back: 'Back', retry: 'Retry', next: 'Next', previous: 'Previous', solution: 'Solution / module', choose: 'Choose a solution', hold: 'Hold expires in', expired: 'Your hold expired. Please select a time again.', acquire: 'Continue / Hold slot', change: 'Change time', conflict: 'This time is no longer available. Your previous hold, if still active, is preserved.', releaseError: 'Could not release the hold. Please try again.', real: 'Live availability. Your slot is held only after you click Continue.', success: 'Request received. NeoTek will confirm your appointment by email.', cancelled: 'Cancel / Back', confirmBooking: 'Submit booking request', time: 'Time', duration: 'Duration' },
}
export function authError(error, copy) { return error.status === 429 ? copy.rate : error.status >= 500 || !error.status ? copy.unavailable : error.status === 401 ? copy.credentials : copy.error }
export function safeReturn(value, language) {
  const prefix = language === 'en' ? '/en' : ''
  return [`${prefix}/booking`, `${prefix}/account/bookings`].includes(value) ? value : `${prefix}/booking`
}
export function statusLabel(status, language) {
  const values = { PENDING: ['Chờ xác nhận', 'Pending'], CONFIRMED: ['Đã xác nhận', 'Confirmed'], CANCELLED: ['Đã hủy', 'Cancelled'], COMPLETED: ['Hoàn thành', 'Completed'], NO_SHOW: ['Vắng mặt', 'No show'] }
  return values[status]?.[language === 'en' ? 1 : 0] ?? status
}
